### ISSUE TITLE
Unreliable isReliable check due to usage of next()

### ISSUE THREAD

**Issue by rarentsenvisymo** [nitotm/efficient-language-detector#11]
Hello, we noticed something weird with your library. When calling `isReliable()` more than once (it depends on how many scores there are), it will sometimes return a different boolean than before making it... unreliable :). This happens due to the usage of `next($this->score)`. It advances the internal pointer of the array. I am not sure on how it should work, there are no test cases for the 24% minimum, otherwise I would have created a merge request. Can you fix this?

**Comment by nitotm** [comment]
Oh..., you are right. I will fix it later.

By the way, what ELD version are you using?

**Comment by rarentsenvisymo** [comment]
Thank you for fixing this in 2.1.2. When I look at the master branch, it seems it has the same problem, as it also uses the next() solution. Did you fix this in another branch?

**Comment by nitotm** [comment]
> Thank you for fixing this in 2.1.2. When I look at the master branch, it seems it has the same problem, as it also uses the next() solution. Did you fix this in another branch?

 `next()` is also used at main branch, but it is used on a new copy of the array every time `$scores = $this->scores();`

To be extra sure, maybe I could also add a reset(), and don't assume at `isReliable()` that the scores pointer is at the start, or I could do `(array_values($scores)[1] ?? 0)`.  
What do you think?

**Comment by rarentsenvisymo** [comment]
What I would do is make the `isReliable` check lazy as well, just like you did for the scores. This way, you only have to calculate it once. The only thing is, LanguageResult has a `public string $language;`, which is mutable. I would not do that, but make it private and expose it via a function. (or make php 8.x the default and use public readonly instead)

The `next($scores)` issue is indeed gone when returning the array via the scores() function, however, next can also return false. I would either:
- assign the score to a local variable and check if it is a float/int and otherwise use a default of 0.0
- go with the suggestion you made
