### ISSUE TITLE
autoloading not working

### ISSUE THREAD

**Issue by JoyceBabu** [nitotm/efficient-language-detector#2]
Autoloading is not working for class `LanguageDetector` on case sensitive file system, since the file is named `languageDetector.php` instead of `LanguageDetector.php`

This is fixed in https://github.com/nitotm/efficient-language-detector/pull/1

**Comment by nitotm** [comment]
Yes, I noticed, not sure what happened, its correct on my local. Will push fix soon.

**Comment by nitotm** [comment]
Fixed, should work now. Any other thing you can let me know.
